spring.application.name=messages-service
server.port=8082

spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500
spring.config.import=optional:consul:

spring.cloud.consul.discovery.enabled=true
spring.cloud.consul.discovery.register=true
spring.cloud.consul.discovery.service-name=${spring.application.name}
spring.cloud.consul.discovery.instance-id=${spring.application.name}-${server.port}
spring.cloud.consul.discovery.prefer-ip-address=true

spring.cloud.consul.service-registry.auto-registration.enabled=true
spring.cloud.consul.service-registry.instance-id=${spring.application.name}

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

logging.level.org.springframework.cloud.consul=DEBUG
logging.level.org.springframework.boot=DEBUG