spring.application.name=messages-service
server.port=8082

# Kafka Consumer Configuration
spring.kafka.bootstrap-servers=localhost:19092,localhost:19093,localhost:19094
spring.kafka.consumer.group-id=messages-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
