spring.application.name=facade-service
server.port=8080

# Kafka Producer Configuration
spring.kafka.bootstrap-servers=localhost:19092,localhost:19093,localhost:19094
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
